services:

  frontend:
    image: ghcr.io/optivem/atdd-accelerator-template-multi-repo-frontend/frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: ghcr.io/optivem/atdd-accelerator-template-multi-repo/backend:latest
    ports:
      - "8081:8081"
    environment:
      - TODOS_API_HOST=https://jsonplaceholder.typicode.com
    networks:
      - app-network

networks:
  app-network:
    driver: bridge